# Nama Workflow
name: Generate Animated Tetris

# Kapan workflow ini dijalankan
on:
  # 1. Sesuai jadwal cron - setiap 6 jam
  schedule:
    - cron: '0 */6 * * *'
    
  # 2. (PENTING) Agar Anda bisa menjalankannya manual
  # untuk pertama kali.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Langkah 1: Checkout repositori Anda
      # Ini agar workflow bisa "melihat" file Anda
      - name: Checkout
        uses: actions/checkout@v3

      # Langkah 2: Buat Animasi Tetris
      # PERBAIKAN: Menggunakan "Dion-g" (D besar) dan versi v1.0.0
      - name: Generate Tetris Animation
        uses: Dion-g/readme-tetris@v1.0.0
        with:
          # Tentukan di mana file SVG akan dibuat
          output: 'assets/tetris-animated.svg'

      # Langkah 3: (INI BAGIAN PENTING YANG BARU)
      # Commit dan Push file SVG yang baru dibuat ke repositori Anda
      - name: Commit and Push generated SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Pesan commit yang akan muncul di riwayat Git Anda
          commit_message: 'feat: Update animated tetris game'
          
          # Beri tahu Aksi ini untuk HANYA meng-commit file ini
          # Pastikan path ini SAMA PERSIS dengan 'output' di Langkah 2
          file_pattern: 'assets/tetris-animated.svg'
          
          # Opsi tambahan untuk memastikan semuanya berjalan lancar
          # Ini akan membuat folder 'assets' jika belum ada
          commit_options: '--force --allow-empty'
          
          # Tambahkan semua file baru
          add: 'assets/tetris-animated.svg'