# Nama Workflow
name: Generate Animated Tetris

# Kapan workflow ini dijalankan
on:
  # 1. Sesuai jadwal cron - setiap 6 jam
  schedule:
    - cron: '0 */6 * * *'
    
  # 2. (PENTING) Agar Anda bisa menjalankannya manual
  # untuk pertama kali.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Check out kode repositori Anda
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Menjalankan Aksi "readme-tetris"
      # Ini adalah "mesin" yang memainkan game dan membuat animasi
      - name: Generate Tetris Animation
        uses: vchime/readme-tetris@master
        with:
          # Path + nama file untuk menyimpan animasi SVG
          # Kita akan menyimpannya di folder 'assets'
          output: 'assets/tetris-animated.svg'
          
          # (Opsional) Teks yang muncul saat game over
          # game_over_text: 'GAME OVER'
          
          # (Opsional) Jika Anda ingin mode 'dark'
          # theme: 'dark'